<div id="kb_buy_link" style="text-align: center; padding: 25px; height: 140px;clear:both; background: #ffffff;">
    <div><span style="font-size:18px;">You are using the Free version of the module. Click here to buy the Paid version which is having the advanced features.</span>
        <br>
        <br>
        <a target="_blank" href="https://www.knowband.com/magento-2-multi-vendor-marketplace"><span style="margin-left:30%;max-width:40% !important;font-size:18px;" class="kb-buy-now-btn">Buy Now</span></a><div>
        </div>
    </div>
</div>

<style>
    .kb-buy-now-btn{
            color: #fff;
            background-color: #72c279;
            border-color: #60ba68;
            display: block;
            width: 100%;
            padding-left: 0;
            padding-right: 0;
            
            margin-bottom: 0;
            font-weight: 400;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            background-image: none;
            border: 1px solid transparent;
            white-space: nowrap;
            padding: 6px 8px;
            font-size: 12px;
            line-height: 1.42857;
            border-radius: 3px;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
    }
    
</style>