<div class="vss_demo_block">
    <img src="<?php echo $this->getViewFileUrl("Knowband_Marketplace::images/seller_reviews_demo.png"); ?>" alt="demo" class="demo_image">
    <div class="middle">
        <span class="vss_overlay_paid_text" >Buy paid version to access all features.</span><br><br>
        <div class="text">
            <a target="_blank" class="vss_free_version_link" href="https://www.knowband.com/magento-2-multi-vendor-marketplace">
                <span class="vss_free_version_button">Buy Now</span>
            </a>
        </div>
    </div>
</div>