<div class = "field">
    <label for = "is_seller" class = "label"><span><?php echo __("Register As Seller"); ?></span></label>
    <div class="control">                                           
        <input type="checkbox" name="is_seller" title="Register as Seller" id="is_seller" class="checkbox"  value="1"/>
        <label for="is_seller" class="label"><?php echo __("Register As Seller"); ?></label><br>
    </div>
</div>
