<!-- Start - Review View Pop up -->
<div id="vssmp-popup" style="display: none;">
    <div class="vssmp-overlay"></div>
    <div class="map-popup">
        <a href="#" class="map-popup-close">×</a>
        <div class="map-popup-heading"><h3>Black Nolita Cami</h3></div>
        <div class="vssmp-map-popup-content vssmp-review-pop-content">
            <div class="vssmp_row vssmp-colortxt-para vssmp-font10">
                Posted on: 01/22/2015 by Dhirender Kumar
            </div>
            <div class="vssmp_row">
                <ul class="vssmp-rating-option-list">
                    <li>
                        <div class="vssmp_small_block vssmp-font13"><span><strong>Overall Rating:</strong></span></div>
                        <div class="vssmp_small_block">
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width:70%;">★★★★★</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="vssmp_small_block vssmp-font12"><strong><span>Value:</span></strong></div>
                        <div class="vssmp_small_block">
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width:60%;">★★★★★</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="vssmp_small_block vssmp-font12"><strong><span>Quality:</span></strong></div>
                        <div class="vssmp_small_block">
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width:90%;">★★★★★</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="vssmp_small_block vssmp-font12"><strong><span>Price:</span></strong></div>
                        <div class="vssmp_small_block">
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width:80%;">★★★★★</div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="vssmp_row">
                <div class="vss_mp_wrapper vssmp_blk_btm_bdr" style="padding-bottom:5px;"><span><strong>Review:</strong></span></div>
                <div class="vss_mp_wrapper vssmp-font12" style="padding-top:5px;">
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 
                        Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo 
                        consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla 
                        facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla 
                        facilisi.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End - Review View Pop up -->