<form action="<?php echo $this->getContinueUrl(); ?>" method="post" class="form-horizontal">
    <div class="box-body">
        <div class="form-group">
            <label class="control-label col-lg-4"><?php echo __('Attribute Set'); ?> <sup><em>*</em></sup></label>
            <div class="col-lg-8">
                <select id="attribute_set_id" class="form-control" name='set'>
                    <?php foreach($this->getAttributeSet() as $attribute){ ?>
                        <option <?php echo (($attribute['value'] == $this->getDefaultAttributeSetId())? 'selected="selected"':''); ?> value="<?php echo $attribute['value']; ?>" ><?php echo $attribute['label']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-4 col-xs-12"><?php echo __('Product Type'); ?> <sup><em>*</em></sup></label>
            <div class="col-lg-8 col-xs-12">
                <select id="product_type" class="form-control" name='type'>
                    <?php foreach($this->getProductTypes() as $key => $type){ ?>
                        <option value="<?php echo $key; ?>" ><?php echo $type; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <div class=" col-lg-12">
            <input type='hidden' name='process_step' value="3" />
            <?php echo $this->getBlockHtml('form_key'); ?>
            <button type="button" class="btn btn-primary pull-right" onclick="getAttributesForProduct()"><?php echo __('Continue'); ?></button>
        </div>
    </div> 
</form>


