<div class="box box-warning collapsed-box">
    <div class="box-header with-border" data-widget="collapse">
        <h3 class="box-title"><?php echo __("Shipped Items"); ?></h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="table-responsive">
            <?php $_items = $this->getShipment()->getAllItems(); ?>
            <?php $_count = count($_items); ?>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th><?php echo __('Product') ?></th>
                        <th><?php echo __('SKU') ?></th>
                        <th class="a-center"><?php echo __('Qty Shipped') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php if($_count > 0){ ?>
                    <?php foreach ($_items as $_item){ ?>
                        <?php if ($_item->getOrderItem()->getIsVirtual() || $_item->getOrderItem()->getParentItem()) { continue; } ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="3"><span class="label label-warning"><?php echo __('No Item Shipped Yet') ?></span></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>