<div class="collapsed-box box">
    <div class="box-header with-border" data-widget="collapse">
        <h3 class="box-title"><?php echo __("Related Products"); ?></h3>
        <div class="box-tools pull-right tab-error-highlighter text-red">
            <i class="fa fa-warning"></i>
        </div>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" ><i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div id="vssmp_related_container" class="box-body">
        <div id="rel-pro-list-filter-list" class="row">
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <input name="sub_pro_filter_id" type="text" class="form-control input-sm" value="<?php echo __('Id'); ?>" data-placeholder="<?php echo __('Id'); ?>" />
            </div>
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <input name="sub_pro_filter_sku" type="text" class="form-control input-sm" value="<?php echo __('Sku'); ?>" data-placeholder="<?php echo __('Sku'); ?>" />
            </div>
            <div class="form-group col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <input type="text" name="sub_pro_filter_name" class="form-control input-sm" value="<?php echo __('Product Name'); ?>" data-placeholder="<?php echo __('Product Name'); ?>" />
            </div>
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <select class="form-control input-sm" name="sub_pro_filter_inv_status">
                    <option value=""><?php echo __('Stock Status'); ?></option>
                    <?php $stock_statuses = $this->getStockStatuses(); ?>
                    <?php foreach($stock_statuses as $row){ ?>
                            <option value="<?php echo $row['value']; ?>"><?php echo $row['label']; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <select class="form-control input-sm" name="sub_pro_filter_attr_set">
                    <option value=""><?php echo __('Select Attribute'); ?></option>
                    <?php $attribute_set = $this->getAttributes(); ?>
                    <?php foreach($attribute_set as $row){ ?>
                            <option value="<?php echo $row['value']; ?>"><?php echo $row['label']; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <button title="" type="button" class="btn btn-default btn-sm" onclick="drawVssmpRelProList('vssmp_rel_products');"><?php echo __('Search'); ?></button>
            </div>
        </div>
        <div class="table-responsive">
            <input type="hidden" name="product[rel_products]" value="" />
            <table id="vssmp_rel_products" class="table table-bordered" style="width: 100%">
                <thead>
                <tr>
                    <th></th>
                    <th><?php echo strtoupper(__('Id')); ?></th>
                    <th width="150"><?php echo __('Product Name'); ?></th>
                    <th><?php echo strtoupper(__('Sku')); ?></th>
                    <th><?php echo __('Attribute'); ?></th>
                    <th><?php echo __('Price'); ?></th>
                    <th><?php echo __('Stock Status'); ?></th>
                    </tr>
                </thead>
                <tbody id="vssmp-associated-product-body">
                    <tr id="product-image-blank-row">
                        <td class="text-center" colspan="7">
                            <span class="label label-warning"><?php echo __('No Data'); ?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    
    var checked_related_products = [];
    <?php foreach($this->getSelectedRelatedProducts() as $p){ ?>
        checked_related_products.push(<?php echo $p; ?>);
    <?php } ?>
    
    require(['jquery', 'Knowband_Marketplace/theme/product'], function(jQuery){
        createRelatedProJson();
    });
    
     
    
    var vssmp_relproducts_datatable_url = "<?php echo $this->getFrontUrl('product', 'getRelatedProducts'); ?>";
    
</script>
