<?php $product = $this->getProduct(); ?>
<div class="collapsed-box box">
    <div class="box-header with-border" data-widget="collapse">
        <h3 class="box-title"><?php echo __("Associated Products"); ?></h3>
        <div class="box-tools pull-right tab-error-highlighter text-red">
            <i class="fa fa-warning"></i>
        </div>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" ><i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div id="vssmp_associate_container" class="box-body">
        <?php if($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ ?>
            <div class="row">
                <div class="form-group col-lg-12">
                    <div class="pull-right">
                        <?php if($this->createSimpleButton()){ ?>
                            <button title="" type="button" class="btn btn-primary btn-sm" onclick="createEmptySimpleProduct('<?php echo $this->getNewEmptyProductUrl(); ?>')"><?php echo __('Create Simple Product'); ?></button>
                        <?php }else{ ?>
                            <button title="" type="button" class="btn btn-primary btn-sm" onclick="alert('<?php echo $this->getLimitOverMsg(); ?>')"><?php echo __('Create Simple Product'); ?></button>
                        <?php } ?>
                        <?php if($product->getId()){ ?>
                            <button title="" type="button" class="btn btn-primary btn-sm" onclick="openVssModal('vssmp-simple-product-popup')"><?php echo __('Quick Create'); ?></button>
                        <?php } ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        <?php } ?>
        <div id="sub-pro-list-filter-list" class="row">
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <input name="sub_pro_filter_id" type="text" class="form-control input-sm" value="<?php echo __('Id'); ?>" data-placeholder="<?php echo __('Id'); ?>" />
            </div>
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <input name="sub_pro_filter_sku" type="text" class="form-control input-sm" value="<?php echo __('Sku'); ?>" data-placeholder="<?php echo __('Sku'); ?>" />
            </div>
            <div class="form-group col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <input type="text" name="sub_pro_filter_name" class="form-control input-sm" value="<?php echo __('Product Name'); ?>" data-placeholder="<?php echo __('Product Name'); ?>" />
            </div>
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <select class="form-control input-sm" name="sub_pro_filter_inv_status">
                    <option value=""><?php echo __('Stock Status'); ?></option>
                    <?php $stock_statuses = $this->getStockStatuses(); ?>
                    <?php foreach($stock_statuses as $row){ ?>
                            <option value="<?php echo $row['value']; ?>"><?php echo $row['label']; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-6">
                <select class="form-control input-sm" name="sub_pro_filter_attr_set">
                    <option value=""><?php echo __('Select Attribute'); ?></option>
                    <?php $attribute_set = $this->getAttributes(); ?>
                    <?php foreach($attribute_set as $row){ ?>
                            <option value="<?php echo $row['value']; ?>"><?php echo $row['label']; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <button title="" type="button" class="btn btn-default btn-sm" onclick="drawVssmpSubProTable('vssmp_sub_products', false);"><?php echo __('Search'); ?></button>
            </div>
        </div>
        <div class="table-responsive">
            <input type="hidden" name="product[rel_products]" value="" />
            <table id="vssmp_sub_products" class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th><?php echo strtoupper(__('Id')); ?></th>
                        <th width="150"><?php echo __('Product Name'); ?></th>
                        <th><?php echo strtoupper(__('Sku')); ?></th>
                        <th><?php echo __('Attribute'); ?></th>
                        <th><?php echo __('Price'); ?></th>
                        <th><?php echo __('Stock Status'); ?></th>
                        <?php if($product->getTypeId() == \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE){ ?>
                        <th><?php echo __('Default Qty'); ?></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody id="vssmp-associated-product-body">
                    <tr id="product-image-blank-row">
                        <td class="text-center" colspan="<?php echo ($product->getTypeId() == \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE)? 8 : 7; ?>">
                            <span class="label label-warning"><?php echo __('No Data'); ?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <?php if($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ ?>
            <?php foreach($this->getLinksJson() as $key => $assoc){ ?>
                <input id='associate_<?php echo $key; ?>' type="hidden" name="product[sub_products][<?php echo $key; ?>]" value='<?php echo $assoc; ?>' />
            <?php } ?>
        <?php }else if($product->getTypeId() == \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE){ ?>
            <input type="hidden" name="product[sub_products]" value='' />
        <?php } ?>

        <?php if($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ ?>
            <input type="hidden" name="sub_product_keys" value='' />
            <input type="hidden" name="affect_product_custom_options" value='1'/>
            <input type="hidden" name="product[configurable_attributes_data]" value='<?php echo $this->getAttributesJson(); ?>' />
            <input type="hidden" name="affect_configurable_product_attributes" value='1'/>
        <?php } ?>
            
        <?php echo $this->getChildHtml('', true, true); ?>
    </div>
</div>

<script type="text/javascript">
    var sub_product_parent = '';
    var sub_load_first_time = true;
    var checked_sub_products = [];
    <?php if($product->getTypeId() == \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE){ ?>
        sub_product_parent = 'grouped';
        <?php foreach($this->getSelectedGroupSubProducts() as $key => $p){ ?>
            checked_sub_products[<?php echo $key; ?>] = [];
            checked_sub_products[<?php echo $key; ?>]['id'] = <?php echo $p['id']; ?>;
            checked_sub_products[<?php echo $key; ?>]['qty'] = <?php echo $p['qty']; ?>;
        <?php } ?>
    <?php }else{ ?>
        sub_product_parent = 'configurable';
        <?php foreach($this->getSelectedProducts() as $p){ ?>
            checked_sub_products.push(<?php echo $p; ?>);
        <?php } ?>
    <?php } ?>
    require(['jquery', 'Knowband_Marketplace/theme/product'], function(jQuery){
       jQuery(document).ready(function(){
           createSubProductJson(); 
           
       })
       
    });
    var vssmp_subproducts_datatable_url = "<?php echo $this->getFrontUrl('product', 'getSubProducts'); ?>";
</script>
